- name: Install X
  hosts: all
  become: yes
  become_user: root
  tasks:
          - name: x base system
            package:
                name: xorg-xinit 
                state: latest

          - name: window manager
            package:
                    name: awesome
                    state: latest

          - name: make default window manager
            command: echo "awesome" > /home/vagrant/.xinitrc

          - name: install basic packages
            package: 
                name:
                  - vim
                  - gnome-terminal
                state: latest


- name: web basic debugging
  hosts: all
  become: yes
  become_user: root
  tasks:
          - name: install browsers
            package:
                    name:
                        - firefox
                        - chromium
                    state: latest

- name: setup java development env
  hosts: all
  become: yes
  become_user: root
  tasks:

          - name: install java
            package:
                    name: openjdk-src
                    state: latest

          - name: install java IDE
            package: 
                    name: eclipse-java
                    state: latest

- name: java advanced debuging
  hosts: all
  become: yes
  become_user: root
  tasks: 
        - name: install visual VM
          package:
                  name: visualvm
                  state: latest

        - name: install dceVM
          package:
                  #name: openjdk-11-jre-dcevm
                  #state: present



- name: setup node development env
  hosts: all
  become: yes
  become_user: root
  tasks:
          - name: install node js
            package:
                  name: nodejs
                  state: present

                  #- name: install js editor
                  #apt:
                  #name: vscode
                  #state: latest

          - name: install node package manager
            package: 
                name: npm
                state: latest

- name: js packaging
  npm: 
        name: @angular/cli
        state: latest
        global: yes

- name: install docker environement
  hosts: all
  become: yes
  become_user: root
  tasks:
          - name: install docker daemon
            package:
                    name: docker
                    state: present


